name:                analisis-googleplay-apps
version:             0.1.0.0
github:              "kennyfh/analisis-googleplay-apps"
license:             BSD3
author:              "Kenny Flores & Jesús Pineda"
maintainer:          "kennyjesus@pm.me"
copyright:           "2022 Kenny Flores & Jesús Pineda"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/analisis-googleplay-apps#readme>

dependencies:
- base >= 4.7 && < 5
- csv
- boxes
- data-default
- array 

library:
  source-dirs: src

executables:
  analisis-googleplay-apps-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analisis-googleplay-apps

tests:
  analisis-googleplay-apps-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analisis-googleplay-apps
